import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import localFont from 'next/font/local'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const windsor = localFont({
  src: '../assets/chainprinter/Chainprinter Regular.ttf',
  variable: '--font-windsor',
})

const chainprinter = localFont({
  src: '../assets/windsor/Windsor Light Condensed Regular.otf',
  variable: '--font-windsor',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <title>YELLOW UNIVERSE</title>
          <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet"/>
      </head>
      <body className={inter.className}>
      <StyledComponentsRegistry>
        {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
